# Generated by Django 5.2.5 on 2025-09-02 14:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="estimated_hours",
            field=models.DecimalField(
                decimal_places=1,
                default=0,
                help_text="Estimated effort in hours (e.g., 1, 1.5, 2)",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
