# Generated by Django 5.2.5 on 2025-09-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_estimated_hours"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="estimated_hours",
        ),
    ]
