# Generated by Django 5.2.5 on 2025-09-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_task_estimated_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated time (in hours) required to complete the task",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional notes, special instructions, or context",
                null=True,
            ),
        ),
    ]
